package com.sav.persistance;

import com.sav.persistance.Appel;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Appel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idappel;
	private String numapp;
	private String emplacement;
	private String mdpbios;
	private String mdpsys;
	private String dosier_sauvegarde;
	private String observationApl;
	private String date_entre;
	private String etat;
	
	
	
	
	public Appel() {
	}
	
	public Appel( String numapp ,  String emplacement , String mdpbios , String mdpsys , String dosier_sauvegarde , String observationApl ,
		String date_entre , String etat)
		

	 {
		this.numapp = numapp;
		this.emplacement = emplacement;
		this.mdpbios = mdpbios;
		this.mdpsys= mdpsys;
		this.dosier_sauvegarde= dosier_sauvegarde;
		this.observationApl= observationApl;
		this.date_entre= date_entre;
		this.etat= etat;
		
		}

	public Integer getIdappel() {
		return idappel;
	}

	public void setIdappel(Integer idappel) {
		this.idappel = idappel;
	}

	public String getNumapp() {
		return numapp;
	}

	public void setNumapp(String numapp) {
		this.numapp = numapp;
	}

	public String getEmplacement() {
		return emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	public String getMdpbios() {
		return mdpbios;
	}

	public void setMdpbios(String mdpbios) {
		this.mdpbios = mdpbios;
	}

	public String getMdpsys() {
		return mdpsys;
	}

	public void setMdpsys(String mdpsys) {
		this.mdpsys = mdpsys;
	}

	public String getDosier_sauvegarde() {
		return dosier_sauvegarde;
	}

	public void setDosier_sauvegarde(String dosier_sauvegarde) {
		this.dosier_sauvegarde = dosier_sauvegarde;
	}

	public String getObservationApl() {
		return observationApl;
	}

	public void setObservationApl(String observationApl) {
		this.observationApl = observationApl;
	}

	public String getDate_entre() {
		return date_entre;
	}

	public void setDate_entre(String date_entre) {
		this.date_entre = date_entre;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((date_entre == null) ? 0 : date_entre.hashCode());
		result = prime
				* result
				+ ((dosier_sauvegarde == null) ? 0 : dosier_sauvegarde
						.hashCode());
		result = prime * result
				+ ((emplacement == null) ? 0 : emplacement.hashCode());
		result = prime * result + ((etat == null) ? 0 : etat.hashCode());
		result = prime * result + ((idappel == null) ? 0 : idappel.hashCode());
		result = prime * result + ((mdpbios == null) ? 0 : mdpbios.hashCode());
		result = prime * result + ((mdpsys == null) ? 0 : mdpsys.hashCode());
		result = prime * result + ((numapp == null) ? 0 : numapp.hashCode());
		result = prime * result
				+ ((observationApl == null) ? 0 : observationApl.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Appel other = (Appel) obj;
		if (date_entre == null) {
			if (other.date_entre != null)
				return false;
		} else if (!date_entre.equals(other.date_entre))
			return false;
		if (dosier_sauvegarde == null) {
			if (other.dosier_sauvegarde != null)
				return false;
		} else if (!dosier_sauvegarde.equals(other.dosier_sauvegarde))
			return false;
		if (emplacement == null) {
			if (other.emplacement != null)
				return false;
		} else if (!emplacement.equals(other.emplacement))
			return false;
		if (etat == null) {
			if (other.etat != null)
				return false;
		} else if (!etat.equals(other.etat))
			return false;
		if (idappel == null) {
			if (other.idappel != null)
				return false;
		} else if (!idappel.equals(other.idappel))
			return false;
		if (mdpbios == null) {
			if (other.mdpbios != null)
				return false;
		} else if (!mdpbios.equals(other.mdpbios))
			return false;
		if (mdpsys == null) {
			if (other.mdpsys != null)
				return false;
		} else if (!mdpsys.equals(other.mdpsys))
			return false;
		if (numapp == null) {
			if (other.numapp != null)
				return false;
		} else if (!numapp.equals(other.numapp))
			return false;
		if (observationApl == null) {
			if (other.observationApl != null)
				return false;
		} else if (!observationApl.equals(other.observationApl))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Appel [idappel=" + idappel + ", numapp=" + numapp
				+ ", emplacement=" + emplacement + ", mdpbios=" + mdpbios
				+ ", mdpsys=" + mdpsys + ", dosier_sauvegarde="
				+ dosier_sauvegarde + ", observationApl=" + observationApl
				+ ", date_entre=" + date_entre + ", etat=" + etat + "]";
	}
	
	
	


}