package com.sav.persistance;

import com.sav.persistance.Fournisseur;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idfournisseur;
	private String nomfour;
	private String adrfour;
	private String mailfour;
	private String gsm1four;
	private String gsm2four;
	private String telfour;
	private String faxfour;
	
	
	
	public Fournisseur() {
	}

	public Fournisseur( String nomfour,  String adrfour,String mailfour, String gsm1four,String gsm2four,String telfour,String faxfour) {
		
		this.nomfour = nomfour;
		this.mailfour = mailfour;
		this.adrfour = adrfour;
		this.gsm1four = gsm1four;
		this.gsm2four = gsm2four;
		this.telfour = telfour;
		this.faxfour = faxfour;
		
	}

	public Integer getIdfournisseur() {
		return idfournisseur;
	}

	public void setIdfournisseur(Integer idfournisseur) {
		this.idfournisseur = idfournisseur;
	}

	public String getNomfour() {
		return nomfour;
	}

	public void setNomfour(String nomfour) {
		this.nomfour = nomfour;
	}

	public String getAdrfour() {
		return adrfour;
	}

	public void setAdrfour(String adrfour) {
		this.adrfour = adrfour;
	}

	public String getMailfour() {
		return mailfour;
	}

	public void setMailfour(String mailfour) {
		this.mailfour = mailfour;
	}

	public String getGsm1four() {
		return gsm1four;
	}

	public void setGsm1four(String gsm1four) {
		this.gsm1four = gsm1four;
	}

	public String getGsm2four() {
		return gsm2four;
	}

	public void setGsm2four(String gsm2four) {
		this.gsm2four = gsm2four;
	}

	public String getTelfour() {
		return telfour;
	}

	public void setTelfour(String telfour) {
		this.telfour = telfour;
	}

	public String getFaxfour() {
		return faxfour;
	}

	public void setFaxfour(String faxfour) {
		this.faxfour = faxfour;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adrfour == null) ? 0 : adrfour.hashCode());
		result = prime * result + ((faxfour == null) ? 0 : faxfour.hashCode());
		result = prime * result + ((gsm1four == null) ? 0 : gsm1four.hashCode());
		result = prime * result + ((gsm2four == null) ? 0 : gsm2four.hashCode());
		result = prime * result
				+ ((idfournisseur == null) ? 0 : idfournisseur.hashCode());
		result = prime * result + ((mailfour == null) ? 0 : mailfour.hashCode());
		result = prime * result + ((nomfour == null) ? 0 : nomfour.hashCode());
		result = prime * result + ((telfour == null) ? 0 : telfour.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Fournisseur other = (Fournisseur) obj;
		if (adrfour == null) {
			if (other.adrfour != null)
				return false;
		} else if (!adrfour.equals(other.adrfour))
			return false;
		if (faxfour == null) {
			if (other.faxfour != null)
				return false;
		} else if (!faxfour.equals(other.faxfour))
			return false;
		if (gsm1four == null) {
			if (other.gsm1four != null)
				return false;
		} else if (!gsm1four.equals(other.gsm1four))
			return false;
		if (gsm2four == null) {
			if (other.gsm2four != null)
				return false;
		} else if (!gsm2four.equals(other.gsm2four))
			return false;
		if (idfournisseur == null) {
			if (other.idfournisseur != null)
				return false;
		} else if (!idfournisseur.equals(other.idfournisseur))
			return false;
		if (mailfour == null) {
			if (other.mailfour != null)
				return false;
		} else if (!mailfour.equals(other.mailfour))
			return false;
		if (nomfour == null) {
			if (other.nomfour != null)
				return false;
		} else if (!nomfour.equals(other.nomfour))
			return false;
		if (telfour == null) {
			if (other.telfour != null)
				return false;
		} else if (!telfour.equals(other.telfour))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Fournisseur [idfournisseur=" + idfournisseur + ", nomfour=" + nomfour
				+ ", adrfour=" + adrfour + ", mailfour=" + mailfour + ", gsm1four="
				+ gsm1four + ", gsm2four=" + gsm2four + ", telfour=" + telfour
				+ ", faxfour=" + faxfour + "]";
	}
}
	