package com.sav.persistance;

import com.sav.persistance.Machine;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Machine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idmachine;
	private String designationMach;
	private String num_serie;
	private String model;
	
	
	
	
	
	public String getNum_serie() {
		return num_serie;
	}

	public void setNum_serie(String num_serie) {
		this.num_serie = num_serie;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Machine() {
	}

	public Machine( String designationMach, String num_serie,
      String model) {
		
		this.designationMach = designationMach;
		this.num_serie = num_serie;
		this.model = model;
		
		
		
		
	}

	public Integer getIdmachine() {
		return idmachine;
	}

	public void setIdmachine(Integer idmachine) {
		this.idmachine = idmachine;
	}

	public String getDesignationMach() {
		return designationMach;
	}

	public void setDesignationMach(String designationMach) {
		this.designationMach = designationMach;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationMach == null) ? 0 : designationMach.hashCode());
		result = prime * result
				+ ((idmachine == null) ? 0 : idmachine.hashCode());
		result = prime * result + ((model == null) ? 0 : model.hashCode());
		result = prime * result
				+ ((num_serie == null) ? 0 : num_serie.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Machine other = (Machine) obj;
		if (designationMach == null) {
			if (other.designationMach != null)
				return false;
		} else if (!designationMach.equals(other.designationMach))
			return false;
		if (idmachine == null) {
			if (other.idmachine != null)
				return false;
		} else if (!idmachine.equals(other.idmachine))
			return false;
		if (model == null) {
			if (other.model != null)
				return false;
		} else if (!model.equals(other.model))
			return false;
		if (num_serie == null) {
			if (other.num_serie != null)
				return false;
		} else if (!num_serie.equals(other.num_serie))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Machine [idmachine=" + idmachine + ", designationMach="
				+ designationMach + ", num_serie=" + num_serie + ", model="
				+ model + "]";
	}

}