package com.sav.persistance;

import com.sav.persistance.Reg_tache;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Reg_tache implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreg_tache;
	
	
	
	public Reg_tache() {
	}


	public Integer getIdreg_tache() {
		return idreg_tache;
	}

	public void setIdreg_tache(Integer idreg_tache) {
		this.idreg_tache = idreg_tache;
		
		
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idreg_tache == null) ? 0 : idreg_tache.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reg_tache other = (Reg_tache) obj;
		if (idreg_tache == null) {
			if (other.idreg_tache != null)
				return false;
		} else if (!idreg_tache.equals(other.idreg_tache))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "Reg_tache [idreg_tache=" + idreg_tache + "]";
	}






	}

