package com.sav.persistance;

import com.sav.persistance.Reg_piece;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Reg_piece implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreg_piece;
	private String qte;
	
	
	
	public Reg_piece() {
	}


	public Integer getIdreg_piece() {
		return idreg_piece;
	}

	public void setIdreg_piece(Integer idreg_piece,String qte) {
		this.idreg_piece = idreg_piece;
		this.qte = qte;
		
	}


	public String getQte() {
		return qte;
	}


	public void setQte(String qte) {
		this.qte = qte;
	}


	public void setIdreg_piece(Integer idreg_piece) {
		this.idreg_piece = idreg_piece;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idreg_piece == null) ? 0 : idreg_piece.hashCode());
		result = prime * result + ((qte == null) ? 0 : qte.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reg_piece other = (Reg_piece) obj;
		if (idreg_piece == null) {
			if (other.idreg_piece != null)
				return false;
		} else if (!idreg_piece.equals(other.idreg_piece))
			return false;
		if (qte == null) {
			if (other.qte != null)
				return false;
		} else if (!qte.equals(other.qte))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "Reg_piece [idreg_piece=" + idreg_piece + ", qte=" + qte + "]";
	}

	
	
	
	
	}

