package com.sav.persistance;

import com.sav.persistance.Reglement;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Reglement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreglement;
	private String totaltache;
	private String prixReg;
	private String totalpiece;
	private String totalrep;
	private String datesortie;
	private String observationReg;
	
	
	
	public Reglement() {
	}

	public Reglement (String totaltache,String prixReg,String totalpiece, String totalrep, String datesortie, String observationReg) {
		
		this.totaltache = totaltache;
		this.prixReg = prixReg;
		this.totalpiece= totalpiece;
		this.totalrep = totalrep;
		this.datesortie= datesortie;
		this.observationReg= observationReg;
		
		
		
	}

	public Integer getIdreglement() {
		return idreglement;
	}

	public void setIdreglement(Integer idreglement) {
		this.idreglement = idreglement;
	}

	public String getTotaltache() {
		return totaltache;
	}

	public void setTotaltache(String totaltache) {
		this.totaltache = totaltache;
	}

	public String getPrixReg() {
		return prixReg;
	}

	public void setPrixReg(String prixReg) {
		this.prixReg = prixReg;
	}

	public String getTotalpiece() {
		return totalpiece;
	}

	public void setTotalpiece(String totalpiece) {
		this.totalpiece = totalpiece;
	}

	public String getTotalrep() {
		return totalrep;
	}

	public void setTotalrep(String totalrep) {
		this.totalrep = totalrep;
	}

	public String getDatesortie() {
		return datesortie;
	}

	public void setDatesortie(String datesortie) {
		this.datesortie = datesortie;
	}

	public String getObservationReg() {
		return observationReg;
	}

	public void setObservationReg(String observationReg) {
		this.observationReg = observationReg;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((datesortie == null) ? 0 : datesortie.hashCode());
		result = prime * result
				+ ((idreglement == null) ? 0 : idreglement.hashCode());
		result = prime * result
				+ ((observationReg == null) ? 0 : observationReg.hashCode());
		result = prime * result + ((prixReg == null) ? 0 : prixReg.hashCode());
		result = prime * result
				+ ((totalpiece == null) ? 0 : totalpiece.hashCode());
		result = prime * result
				+ ((totalrep == null) ? 0 : totalrep.hashCode());
		result = prime * result
				+ ((totaltache == null) ? 0 : totaltache.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reglement other = (Reglement) obj;
		if (datesortie == null) {
			if (other.datesortie != null)
				return false;
		} else if (!datesortie.equals(other.datesortie))
			return false;
		if (idreglement == null) {
			if (other.idreglement != null)
				return false;
		} else if (!idreglement.equals(other.idreglement))
			return false;
		if (observationReg == null) {
			if (other.observationReg != null)
				return false;
		} else if (!observationReg.equals(other.observationReg))
			return false;
		if (prixReg == null) {
			if (other.prixReg != null)
				return false;
		} else if (!prixReg.equals(other.prixReg))
			return false;
		if (totalpiece == null) {
			if (other.totalpiece != null)
				return false;
		} else if (!totalpiece.equals(other.totalpiece))
			return false;
		if (totalrep == null) {
			if (other.totalrep != null)
				return false;
		} else if (!totalrep.equals(other.totalrep))
			return false;
		if (totaltache == null) {
			if (other.totaltache != null)
				return false;
		} else if (!totaltache.equals(other.totaltache))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Reglement [idreglement=" + idreglement + ", totaltache="
				+ totaltache + ", prixReg=" + prixReg + ", totalpiece="
				+ totalpiece + ", totalrep=" + totalrep + ", datesortie="
				+ datesortie + ", observationReg=" + observationReg + "]";
	}

}