package com.sav.persistance;

import com.sav.persistance.Service;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Service implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idservice;
	private String designationSer;
	
	
	
	
	public Service() {
	}

	public Service( String designationSer) {
		
		this.designationSer = designationSer;
		
		
	}

	public Integer getIdservice() {
		return idservice;
	}

	public void setIdservice(Integer idservice) {
		this.idservice = idservice;
	}

	public String getDesignationSer() {
		return designationSer;
	}

	public void setDesignationSer(String designationSer) {
		this.designationSer = designationSer;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationSer == null) ? 0 : designationSer.hashCode());
		result = prime * result
				+ ((idservice == null) ? 0 : idservice.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Service other = (Service) obj;
		if (designationSer == null) {
			if (other.designationSer != null)
				return false;
		} else if (!designationSer.equals(other.designationSer))
			return false;
		if (idservice == null) {
			if (other.idservice != null)
				return false;
		} else if (!idservice.equals(other.idservice))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Service [idservice=" + idservice + ", designationSer="
				+ designationSer + "]";
	}
	



}

	