package com.sav.persistance;

import com.sav.persistance.Statut;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Statut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstatut;
	private String designationStat;
	
	
	
	
	public Statut() {
	}

	public Statut( String designationStat) {
		
		this.designationStat = designationStat;
		
		
	}

	public Integer getIdstatut() {
		return idstatut;
	}

	public void setIdstatut(Integer idstatut) {
		this.idstatut = idstatut;
	}

	public String getDesignationStat() {
		return designationStat;
	}

	public void setDesignationStat(String designationStat) {
		this.designationStat = designationStat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationStat == null) ? 0 : designationStat.hashCode());
		result = prime * result
				+ ((idstatut == null) ? 0 : idstatut.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Statut other = (Statut) obj;
		if (designationStat == null) {
			if (other.designationStat != null)
				return false;
		} else if (!designationStat.equals(other.designationStat))
			return false;
		if (idstatut == null) {
			if (other.idstatut != null)
				return false;
		} else if (!idstatut.equals(other.idstatut))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Statut [idstatut=" + idstatut + ", designationStat="
				+ designationStat + "]";
	}
	



}

	