package com.sav.persistance;

import com.sav.persistance.Type_four;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Type_four implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtype_four;
	private String nomtype_four;
	
	
	
	
	public Type_four() {
	}

	public Type_four( String nomtype_four) {
		
		this.nomtype_four = nomtype_four;
		
		
	}

	public Integer getIdtype_four() {
		return idtype_four;
	}

	public void setIdtype_four(Integer idtype_four) {
		this.idtype_four = idtype_four;
	}

	public String getNomtype_four() {
		return nomtype_four;
	}

	public void setNomtype_four(String nomtype_four) {
		this.nomtype_four = nomtype_four;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((nomtype_four == null) ? 0 : nomtype_four.hashCode());
		result = prime * result
				+ ((idtype_four == null) ? 0 : idtype_four.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Type_four other = (Type_four) obj;
		if (nomtype_four == null) {
			if (other.nomtype_four != null)
				return false;
		} else if (!nomtype_four.equals(other.nomtype_four))
			return false;
		if (idtype_four == null) {
			if (other.idtype_four != null)
				return false;
		} else if (!idtype_four.equals(other.idtype_four))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Type_four [idtype_four=" + idtype_four + ", nomtype_four="
				+ nomtype_four + "]";
	}
	



}

	